name: Convert Markdown to docx and PDF

on:
  push:
    branches:
      - main
    paths:
      - resume.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-roboto

      - name: Set output filenames
        id: set-filenames
        run: |
          filename=$(cat name.txt | tr -d '\n') # Read the name from name.txt
          echo "pdf_filename=${filename}_resume.pdf" >> $GITHUB_ENV
          echo "docx_filename=${filename}_resume.docx" >> $GITHUB_ENV

      - name: Convert Markdown to PDF and docx
        run: |
          pandoc resume.md -o output/${{ env.pdf_filename }} --pdf-engine=xelatex -V mainfont="Roboto" -V geometry:top=0.5in,bottom=0.5in,left=0.5in,right=0.5in -V linkcolor=blue
          pandoc resume.md -o output/${{ env.docx_filename }} # --reference-doc=templates/reference.docx

      - name: Commit generated files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          
          git add output/${{ env.pdf_filename }}
          git add output/${{ env.docx_filename }}
          
          git commit -m "Add docx and PDF files to output" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
